# Generated by Django 6.0.6 on 2026-07-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Pasta', 'Pasta'), ('Biryani', 'Biryani'), ('Dessert', 'Dessert'), ('Drink', 'Drink'), ('Salad', 'Salad')], max_length=50),
        ),
    ]
