# Generated by Django 6.0.6 on 2026-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customizationoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationoption',
            name='selection_type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=10),
        ),
    ]
