# Generated by Django 6.0.6 on 2026-07-31 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='parking_info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Notified', 'Notified'), ('Seated', 'Seated'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='users.userprofile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='users.restaurant')),
            ],
        ),
    ]
